node_dict = {
    "method":       "_METH",
    "constant":     "_CONST",
    "attribute":    "_ATTR",
    "tex":          "_TEX",
    "hex":          "_HEX",
    "osltri":       "_OSLTRI",
    "triplanar":    "_TRI",
    "hextri":       "_HEXTRI",
    "noise":        "_NOISE",
    "custom":       "_CUST",
    "none":         "_NONE",
    "detail":       "_DETAIL",
    "detail_cc":    "_DETAIL_CC",
    "roundcorner":  "_ROUNDCORNER",
    "tex_cc":       "_TEX_CC",
    "aces":         "_ACES",
    "clamp":        "_CLAMP",
    "source":       "_SRC",
    "cleansource":  "_CLNSRC",
    "output":       "_OUT",
    "kmablend":     "_KMABLEND",
    "detailout":    "detailOUT",
    "bumpdetailout":"bumpdetailOUT",
    "dispdetailout":"dispdetailOUT",
    "weights":      "mat_weights_REFERENCE",
    "solo":         "SOLO",
    "aovout":       "AOVOUT",
    "sprite":       "SPRITE",
    "shader":       "SHADER",
    "material":     "MATERIAL",
}